from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


def repo_root() -> Path:
    env = os.environ.get("GEMINI_OP_REPO_ROOT", "").strip()
    if env:
        return Path(env).expanduser().resolve()
    return Path(__file__).resolve().parents[1]


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def count_local_skills(root: Path) -> int:
    skills_dir = root / "agents" / "skills"
    if not skills_dir.exists():
        return 0
    return len(list(skills_dir.glob("skill_*.py")))


def global_skills_count() -> int:
    # Per AGENTS.md: this is the authoritative registry.
    reg_path = Path(os.environ.get("GEMINI_OP_SKILLS_REGISTRY", str(Path.home() / "findings_reference_optimized.json")))
    if not reg_path.exists():
        return 0
    try:
        data = read_json(reg_path)
        skills = data.get("skills_by_name", {}) or {}
        return int(len(skills))
    except Exception:
        return 0


def render(root: Path) -> str:
    local = count_local_skills(root)
    global_n = global_skills_count()
    has_brain = (root / "scripts" / "sovereign_brain.py").exists()
    has_mouth = (root / "scripts" / "mouth.py").exists()

    lines: list[str] = []
    lines.append("# App Status")
    lines.append("")
    lines.append("This file is generated by `scripts/update_app_status.py`.")
    lines.append("It is the single source of truth for the current runtime shape and counts.")
    lines.append("")
    lines.append("## Entry Points")
    lines.append("- `start.ps1 -Council` (multi-agent council orchestrator)")
    if has_brain:
        lines.append("- `start.ps1 -Brain -Dashboard` (optional; requires Brain modules)")
        lines.append("- `scripts/sovereign_brain.py` (optional; direct brain entry)")
    if has_mouth:
        lines.append("- `start.ps1 -Mouth` (optional; single-terminal REPL -> NeuralBus -> Executive Core)")
    lines.append("")
    lines.append("## Intelligence Routing")
    lines.append("- Council hybrid router: `scripts/agent_runner_v2.py`")
    lines.append("- Local fallback model (default): `phi4` via Ollama")
    lines.append("")
    lines.append("## Governance")
    lines.append("- Council supervisor (deterministic verify/challenge + safe summaries): `scripts/council_supervisor.py`")
    lines.append("- Patch auto-apply (fail-closed): `scripts/council_patch_apply.py`")
    lines.append("")
    lines.append("## Reliability / Red-Team")
    lines.append("- Council bus (jsonl message bus): `scripts/council_bus.py`")
    lines.append("- World-state rebuilder (blackout/drift resilience): `scripts/state_rebuilder.py`")
    lines.append("")
    lines.append("## Skills")
    lines.append(f"- Local skills (`agents/skills/skill_*.py`): **{local}**")
    lines.append(f"- Global skills (skills registry): **{global_n}**")
    lines.append("- External skills sources (bridged into council prompts): `C:\\Users\\<you>\\.codex\\skills`, `C:\\Users\\<you>\\.gemini\\skills` (override via `GEMINI_OP_SKILLS_DIR_CODEX` / `GEMINI_OP_SKILLS_DIR_GEMINI`).")
    lines.append("- Skill selection + pack rendering: `scripts/skill_bridge.py` -> `<run_dir>/state/skills_selected.md` (auto-injected by `scripts/triad_orchestrator.ps1`).")
    lines.append("")
    lines.append("## UIs")
    lines.append("- Streamlit dashboard: `scripts/dashboard.py` (includes `GOVERNANCE`, `SKILLS`, and `DOCS` tabs)")
    lines.append("- TUI dashboard: `scripts/tui_dashboard.py` (includes a `DOCS` panel rendering `docs/APP_STATUS.md`)")
    lines.append("")
    lines.append("## Config")
    lines.append("- Shared profiles: `config/config.base.toml`, `config/profiles/config.core.toml`, `config/profiles/config.full.toml`, `config/profiles/config.max.toml`")
    lines.append("- Local overrides (ignored): `config/config.local.toml`")
    lines.append("- Runtime assembled (ignored): `config/config.active.toml`")
    lines.append("")
    lines.append("## Doc Policy")
    lines.append("- Any functional change must be accompanied by doc updates.")
    lines.append("- The pre-commit hook auto-refreshes this file and will block commits if it is stale.")
    lines.append("- Launch-time guardrails: `scripts/check_docs.ps1` is executed by `start.ps1` and `scripts/sovereign_brain.py` (unless skipped).")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate docs/APP_STATUS.md (and optionally check it).")
    ap.add_argument("--check", action="store_true", help="Fail if docs/APP_STATUS.md is not up to date.")
    args = ap.parse_args()

    root = repo_root()
    out = root / "docs" / "APP_STATUS.md"
    out.parent.mkdir(parents=True, exist_ok=True)

    expected = render(root)
    if args.check:
        current = out.read_text(encoding="utf-8", errors="ignore") if out.exists() else ""
        if current != expected:
            raise SystemExit("docs/APP_STATUS.md is stale. Run: python scripts/update_app_status.py")
        return 0

    out.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
